== Werkzeuge

=== Grundlagen
Die Pflege von Daten- und Modell-Repositories ist entscheidend für das Funktionieren derjenigen INTERLIS-Werkzeuge, die sich darauf abstützen. Bei einer umfangreichen Anzahl von Modellen und Datensätzen ist eine manuelle Nachführung von _ilimodels.xml_ und _ilidata.xml_ jedoch zeitaufwändig und fehleranfällig. Aus diesem Grund wurde ein spezielles Software-Werkzeug entwickelt, um die Pflege der Index-Dateien zu automatisieren.footnote:[Die Datei _ilisite.xml_ ist im Gegensatz zu den anderen beiden Index-Dateien sehr statisch; einmal eingerichtet und mit Verweisen auf über- und untergeordnete Repositories versehen, werden daran nur in Ausnahmefällen Änderungen vorgenommen. Es besteht zurzeit kein Software-Werkzeug, welches ilisite.xml automatisch.] Zudem gibt es die eine oder andere Option in den herkömmlichen INTERLIS Werkzeugen, welche den Umgang mit Repositories erleichtert.

=== Das Werkzeug ilimanager
Die Software _ilimanager_ footnote:[Die Software befindet zurzeit in einer Beta-Phase und ist noch nicht offiziell verfügbar. Weitere Details zum Entwicklungsstand können über das https://github.com/claeis/ilimanager[github-Repository von ilimanager] in Erfahrung gebracht werden.] bietet Funktionalität an, um die Arbeit mit Index-Dateien zu automatisieren. Es stehen folgende Funktionen zur Verfügung:

*Pflege von ilimodels.xml*

* Erstellen von ilimodels.xml, wobei ein lokales Verzeichnis angegeben wird, das nach Modelldateien (.ili) durchsucht wird.
* Aktualisieren von ilimodels.xml aufgrund von Veränderungen im angegebenen Verzeichnis.
// @todo.2022-12-03: Umzug von Option --listModels von ili2c nach ilimanager abwarten (siehe ilimanager#1)
// * `--listModels` zum Auflisten aller (erreichbaren?) Modelle.

*Pflege von ilidata.xml*

* Erstellen von ilidata.xml, wobei ein lokales Verzeichnis angegeben wird, das nach Transferdateien (.xtf resp. .itf) durchsucht wird.
* Aktualisieren von ilidata.xml aufgrund von Veränderungen im angegebenen Verzeichnis.
// @todo.2022-12-03: Umzug von Option --listData von ili2c nach ilimanager abwarten (siehe ilimanager#2)
// * `--listData` zum Auflisten aller (erreichbaren?) Datensätze.

*Repository-Funktionen*

* Klonen eines bestehenden Repositorys.

Beispiele und die Dokumentation des gesamten Funktionsumfangs von _ilimanager_ sind in der https://github.com/claeis/ilimanager/blob/main/docs/ilimanager.rst[Dokumentation auf github] beschrieben.footnote:[Am Zweiten INTERLIS Anwender:innen-Treffen im Herbst 2022 fand ein Workshop zum Thema INTERLIS Repositorys statt. Die Unterlagen des Workshops sind im https://interlis.discourse.group/t/2-interlis-anwender-innen-treffen/28/2?u=beistehen[INTERLIS-Forum] verfügbar.]


=== Integritätsprüfung eines Model Repository
Der INTERLIS Compiler (https://www.interlis.ch/downloads/ili2c[ili2c]) bietet die Option an, um ein Model Repository und alle darin indexierten Modelle zu prüfen. Die Option lautet `--check-repo-ilis` und sie wird folgendermassen aufgerufen:

----
java -jar ili2c.jar --check-repo-ilis <url>
----

[NOTE]
Der Kanton Solothurn betreibt basierend auf dieser Funktionalität einen Online-Dienst namens https://geo.so.ch/repochecker[Repo Checker], der regelmässig alle Repositories prüft, die online verfügbar sind (mit \https://models.interlis.ch als Einstiegspunkt).

=== Integritätsprüfung eines Data Repository
Der INTERLIS Validator (https://www.interlis.ch/downloads/ilivalidator[ilivalidator]) bietet die Option an, um ein Data Repository und alle darin indexierten Datensätze zu prüfen. Die Option lautet `--check-repo-data` und sie wird folgendermassen aufgerufen:

----
java -jar ilivaldator.jar --check-repo-data <url>
----
